---
- name: Create Oracle Database using dbca
  hosts: all
  become: true
  become_user: oracle  # Specify the user to become (oracle in this case)
  environment:
    # Add any necessary environment variables for Oracle setup
    ORACLE_HOME: /u01/app/oracle/product/19.3/dbhome_1
    LD_LIBRARY_PATH: /u01/app/oracle/product/19.3/dbhome_1/lib:/lib:/usr/lib

  vars:
    PDB_NAME: "test"
    DATA_DIR: "/u01/app/oracle"
    ORACLE_SID: "test1"
    MEMORY: 24
  tasks:
    - name: Start Oracle Listener using lsnrctl
      command: /u01/app/oracle/product/19.3/dbhome_1/bin/lsnrctl start
      ignore_errors: yes
    - name: Run dbca command
      command: >
        /u01/app/oracle/product/19.3/dbhome_1/bin/dbca -silent -createDatabase
        -templateName General_Purpose.dbc
        -gdbname "{{ ORACLE_SID }}"
        -sid "{{ ORACLE_SID }}"
        -responseFile NO_VALUE
        -characterSet AL32UTF8
        -sysPassword SysPassword1
        -systemPassword SysPassword1
        -createAsContainerDatabase true
        -numberOfPDBs 1
        -pdbName "{{ PDB_NAME }}"
        -pdbAdminPassword PdbPassword1
        -databaseType MULTIPURPOSE
        -memoryMgmtType auto_sga
        -totalMemory "{{ MEMORY }}"
        -storageType FS
        -datafileDestination "{{ DATA_DIR }}"
        -redoLogFileSize 50
        -emConfiguration NONE
        -ignorePreReqs
